theme[main_bg]="#19191e"
theme[main_fg]="#a6abb4"
theme[hi_fg]="#d2bd76
theme[selected_bg]="#23222c"
theme[selected_fg]="#fbfafc"

theme[title]="#9675d2"
theme[inactive_fg]="#9b9fa8"

theme[graph_text]="#fbfafc"
theme[meter_bg]="#2d2c33"
theme[proc_misc]="#8f939d"

theme[cpu_box]="#cc707e"
theme[mem_box]="#cf8f70"
theme[net_box]="#73bd63"
theme[proc_box]="#9675d2"

theme[div_line]="#505050"

theme[process_start]="#9675d2"
theme[process_mid]="#694ca4"
theme[process_end]="#8f939d"
